language: python
python:
  - "3.6"
script: python tests/test_all_of_the_units.py
branches:
 only:
  - master
install:
  - pip install -r requirements.txt

repo_token: HAGAyvMPzZ4ZJKPB9OnXxRilcR4bPgk1L

